services:
  api:
    build: .
    container_name: api_react_microsoft_platform
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./src:/app/src
      - /app/node_modules
